"""Application configuration via environment variables."""

from pydantic import Field
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    """Application settings loaded from environment variables."""

    # Database
    DATABASE_URL: str

    # Security
    SECRET_KEY: str
    ACCESS_TOKEN_EXPIRE_MINUTES: int = 15
    REFRESH_TOKEN_EXPIRE_DAYS: int = 7
    ALGORITHM: str = "HS256"
    # Independent secret used to sign the public-budget verification
    # cookies (ADR 0006). Falls back to ``SECRET_KEY`` for local/dev
    # convenience, but production deploys must set it explicitly so a
    # leak of one key does not compromise the other.
    BUDGET_PUBLIC_SECRET_KEY: str = ""

    # Environment
    ENVIRONMENT: str = "development"
    ALLOWED_ORIGINS: str = ""

    # Rate limiting
    LOGIN_RATE_LIMIT: str = "5/minute"
    REGISTER_RATE_LIMIT: str = "3/hour"

    # Testing
    TESTING: bool = False

    # Optional sales demo. Disabled by default so paid/offline installations
    # never expire. For a hosted trial, set TRIAL_MODE=true and pin
    # TRIAL_STARTED_AT to an ISO-8601 UTC timestamp; restarts then cannot reset
    # the clock. The commercial trial length is three days by default.
    TRIAL_MODE: bool = False
    TRIAL_STARTED_AT: str = ""
    TRIAL_DAYS: int = 3

    # Commercial local-install licensing. Kept disabled by default so hosted
    # deployments and development are unchanged. Generic paid Windows packages
    # explicitly enable it in docker-compose.client.yml.
    LICENSE_ENFORCEMENT: bool = False
    LICENSE_SERVER_URL: str = ""
    # Base64-encoded PEM Ed25519 public key. The matching private key lives only
    # on the remote Dentora license service.
    LICENSE_PUBLIC_KEY_B64: str = ""
    # Generated by START_DENTORA.bat from the Windows host MachineGuid.
    LICENSE_MACHINE_FINGERPRINT: str = ""
    LICENSE_HTTP_TIMEOUT_SECONDS: float = 5.0
    LICENSE_REFRESH_RETRY_MINUTES: int = 60

    # Public booking cloud synchronization. Local Dentora only makes
    # outbound HTTPS requests; the cloud never connects inbound to the clinic.
    BOOKING_CLOUD_BASE_URL: str = ""
    BOOKING_SYNC_HTTP_TIMEOUT_SECONDS: float = 10.0

    # Module system
    DENTORA_DEV_MODULE_SCAN: bool = True  # Fallback filesystem scan for dev
    # Host-mounted path where `frontend/modules.json` lives. The backend
    # writes this file whenever a module with a Nuxt layer is
    # installed/uninstalled so the Nuxt host picks up `extends` on next
    # build. docker-compose mounts `./frontend` → `/host_frontend`.
    DENTORA_FRONTEND_ROOT: str = "/host_frontend"
    # Absolute path INSIDE the frontend container where
    # `backend/app/modules` is mounted (see docker-compose). The writer
    # uses this prefix when rendering layer paths in `modules.json` so
    # the frontend container can resolve them with `extends`. In
    # production (single container / bundled deploy) this can be set to
    # the same path the backend sees for modules, in which case no
    # translation happens.
    DENTORA_MODULE_LAYERS_MOUNT: str = "/module_layers"
    # The backend-container path at which module packages live. Stripped
    # from absolute layer paths before the MOUNT prefix is applied. Rare
    # to override; exists for non-standard container layouts.
    DENTORA_MODULE_PKG_ROOT: str = "/app/app/modules"

    # Storage configuration
    STORAGE_BACKEND: str = "local"
    STORAGE_LOCAL_PATH: str = "/app/storage"
    STORAGE_MAX_FILE_SIZE: int = 10 * 1024 * 1024  # 10MB
    STORAGE_ALLOWED_MIME_TYPES: str = "application/pdf,image/jpeg,image/png"

    # Dental 3D Phase 5.2 — optional, operator-managed CBCT nerve inference.
    # Dentora does not bundle medical-model weights. An empty URL is an
    # explicit, safe "missing_model" state rather than a simulated result.
    DENTAL_3D_NERVE_INFERENCE_URL: str = ""
    DENTAL_3D_NERVE_INFERENCE_TOKEN: str = ""
    DENTAL_3D_NERVE_INFERENCE_TIMEOUT_SECONDS: float = Field(default=120.0, gt=0, le=3600)
    DENTAL_3D_NERVE_MAX_INSTANCES: int = Field(default=512, ge=1, le=2048)
    DENTAL_3D_NERVE_MAX_INPUT_BYTES: int = Field(
        default=256 * 1024 * 1024, ge=1024, le=2 * 1024 * 1024 * 1024
    )
    DENTAL_3D_NERVE_LOW_CONFIDENCE_THRESHOLD: float = Field(default=0.6, ge=0, le=1)

    # Patient-specific IOS→CBCT registration. DentalSegmentator remains an
    # operator-managed service; no model weights or PyTorch ship in Dentora.
    DENTAL_3D_DENTAL_SEGMENTATOR_URL: str = ""
    DENTAL_3D_DENTAL_SEGMENTATOR_TOKEN: str = ""
    DENTAL_3D_DENTAL_SEGMENTATOR_TIMEOUT_SECONDS: float = Field(default=900.0, gt=0, le=7200)
    DENTAL_3D_REGISTRATION_MAX_INSTANCES: int = Field(default=512, ge=1, le=2048)
    DENTAL_3D_REGISTRATION_MAX_INPUT_BYTES: int = Field(
        default=256 * 1024 * 1024, ge=1024, le=2 * 1024 * 1024 * 1024
    )
    DENTAL_3D_REGISTRATION_VOXEL_SIZE_MM: float = Field(default=1.0, gt=0, le=10)
    DENTAL_3D_REGISTRATION_GLOBAL_DISTANCE_MM: float = Field(default=3.0, gt=0, le=50)
    DENTAL_3D_REGISTRATION_ICP_DISTANCE_MM: float = Field(default=1.5, gt=0, le=20)
    DENTAL_3D_REGISTRATION_ICP_MAX_ITERATIONS: int = Field(default=50, ge=1, le=500)

    @property
    def storage_allowed_mime_types_list(self) -> list[str]:
        """Parse allowed MIME types as list."""
        return [t.strip() for t in self.STORAGE_ALLOWED_MIME_TYPES.split(",")]

    # Email configuration
    EMAIL_ENABLED: bool = True
    EMAIL_PROVIDER: str = "console"  # console, smtp (sendgrid, mailgun in future)

    # SMTP configuration
    EMAIL_SMTP_HOST: str = "smtp.gmail.com"
    EMAIL_SMTP_PORT: int = 587
    EMAIL_SMTP_TLS: bool = True
    EMAIL_SMTP_USER: str = ""
    EMAIL_SMTP_PASSWORD: str = ""

    # Default sender
    EMAIL_FROM_ADDRESS: str = "noreply@dentora.example"
    EMAIL_FROM_NAME: str = "Dentora"

    # Copilot / agentic layer (app/core/llm/). OpenAI is the only live
    # provider in v1; per-clinic `copilot_settings` overrides provider +
    # model. (ANTHROPIC_API_KEY + its model default land with that
    # provider.)
    OPENAI_API_KEY: str = ""
    AI_GATEWAY_BASE_URL: str = ""
    COPILOT_PROVIDER_DEFAULT: str = "openai"
    COPILOT_MODEL_CHAT_OPENAI: str = "gpt-5.4-mini"
    COPILOT_MAX_TOKENS: int = 4096
    COPILOT_REDACTION_DEFAULT: bool = True

    @property
    def ai_gateway_base_url(self) -> str:
        """Resolve the OpenAI-compatible Dentora AI gateway base URL."""
        configured = self.AI_GATEWAY_BASE_URL.strip()
        if configured:
            return configured.rstrip("/") + "/"

        server = self.LICENSE_SERVER_URL.strip()
        if not server:
            return ""

        return server.rstrip("/") + "/ai/v1/"

    @property
    def allowed_origins_list(self) -> list[str]:
        """Parse ALLOWED_ORIGINS as comma-separated list."""
        if not self.ALLOWED_ORIGINS:
            return []
        return [origin.strip() for origin in self.ALLOWED_ORIGINS.split(",")]

    model_config = SettingsConfigDict(env_file=".env", env_file_encoding="utf-8")


settings = Settings()
